receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:6004
      http:
        endpoint: 0.0.0.0:6006

processors:
  batch: {} # Add a batch processor for traces and metrics

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:9464" # Expose metrics for Prometheus scraping

  otlp/localcollector:
    endpoint: http://localhost:4317
    tls:
      insecure: true

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/localcollector, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug] # Export metrics to Prometheus and debug logs