receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${COLLECTOR_ENDPOINT}:${COLLECTOR_GRPC_PORT}

processors:
  batch: {} # Add a batch processor for traces and metrics

exporters:
  debug:
    verbosity: detailed

  otlp/localcollector:
    endpoint: ${COLLECTOR_ENDPOINT}:${COLLECTOR_GRPC_PORT}
    tls:
      insecure: true

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/localcollector, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/localcollector, debug]